### PR TITLE
Fix RTD preview message rendering

### PR DESCRIPTION
**Pull request by egeakman**
See: https://github.com/readthedocs/actions/issues/34#issuecomment-1849854607

PS: pre-commit is failing because of https://github.com/pypa/hatch/issues/1113

### CODE REVIEW

**Comment by ofek** [comment]
> PS: pre-commit is failing because of https://github.com/pypa/hatch/issues/1113

https://github.com/sphinx-contrib/sphinx-lint/pull/106

**Comment by hugovk** [comment]
Thanks for the PR! Let's wait a little bit, I'd prefer an upstream fix at https://github.com/readthedocs/actions so we don't need to apply this to all the repos.

**Comment by egeakman** [comment]
> Thanks for the PR! Let's wait a little bit, I'd prefer an upstream fix at https://github.com/readthedocs/actions so we don't need to apply this to all the repos.

Alright! The fix is at https://github.com/readthedocs/actions/pull/32, if anyone's wondering. Though the RTD team can not reproduce the fix.

**Comment by egeakman** [comment]
Closing the PR for now

**Pull request closed without merging**
