### PR TITLE
Make links clickable in 2022 minutes

### PR DESCRIPTION
**Pull request by hugovk**
----
📚 Documentation preview 📚: https://docs-community--125.org.readthedocs.build/

### CODE REVIEW

**Review by egeakman — APPROVED** [review]
Looks good! Do we also want to fix these (the unrendered emojis e.g. ``:tada:``)?
image

**Comment by hugovk** [comment]
Good idea! Just one in 2022 and just one in 2023. I'll fix the 2023 in the 2023 PR.

**Comment by hugovk** [comment]
Oh, and some others too, will also fix them.

**Comment by hugovk** [comment]
> I'll fix the 2023 in the 2023 PR.

I was too quick to merge that one, here it is instead :)

**Pull request merged**
