### PR TITLE
Automatically edit PRs with link to RTD preview

### PR DESCRIPTION
**Pull request by hugovk**
Let's try this by RTD: https://github.com/readthedocs/actions/tree/v1/preview

> GitHub Action that automatically edits Pull Requests' descriptions with a link to documentation's preview on Read the Docs.

For example: 

* https://github.com/poliastro/poliastro/blob/main/.github/workflows/documentation-links.yaml
* ->
* https://github.com/poliastro/poliastro/pull/1613

image

### CODE REVIEW

**Comment by hugovk** [comment]
I think this needs to be merged before it's active.

**Comment by humitos** [comment]
@hugovk yes, you have to merge the PR to be executed. I haven't find a way on GitHub to be able to test these actions from a Pull Request unfortunately.

**Comment by CAM-Gerlach** [comment]
> yes, you have to merge the PR to be executed. I haven't find a way on GitHub to be able to test these actions from a Pull Request unfortunately.

Testing it on your fork works if it doesn't require something specific on the upstream, and I believe pushing it to a new upstream branch and then submitting a PR against that branch might work too, depending on the workflow trigger.

**Comment by hugovk** [comment]
Thank you @humitos (and RTD) for the Action (and RTD)!

**Comment by humitos** [comment]
@CAM-Gerlach 

> Testing it on your fork works

That's a pretty simple and great idea! 💯 . I haven't thought about this before. I will start using this workflow from now on 👍🏼 . Thanks!

**Pull request merged**
