### PR TITLE
Add logo to docs site

### PR DESCRIPTION
**Pull request by hugovk**
Adds the one used for the Discord.

So instead of the default RTD icon we get a favicon that's also distinct from the other Python sites:

image

----
:books: Documentation preview :books:: https://docs-community--91.org.readthedocs.build/en/91/

### CODE REVIEW

**Comment by egeakman** [comment]
I think a transparent background might look better

**Comment by egeakman** [comment]
I can't upload webp here so here is the png. I can send the webp to you or open a new pull request

docs-community-logo-transparent

**Comment by hugovk** [comment]
Please could you zip the webp? It should upload then.

**Comment by egeakman** [comment]
[docs-community-logo-transparent.zip](https://github.com/python/docs-community/files/13078504/docs-community-logo-transparent.zip)

**Comment by egeakman** [comment]
Looks good to me 👍 

image

**Comment by ezio-melotti** [comment]
The black feather doesn't have much contrast with the black background.

Maybe it could be outlined or a semi transparent background could be added instead? Having an opaque circular background might also be an option.

**Comment by hugovk** [comment]
Something like this?

image

**Comment by egeakman** [comment]
> Something like this?
> 
> --

I'm OK with both versions, what do you guys think about an outer stroke for the feather?

image

**Comment by bskinn** [comment]
Drive-by opinion, I think the white outer stroke is a much better option than adding the white field. The quill is still poorly defined against the white field, even though it _is_ easier to tell that it's a quill & inkpot.

I like [this one with the white stroke](https://github.com/python/docs-community/pull/91#issuecomment-1775932408) quite a bit. That stroke width seems good... a bit of transparency on the stroke seems like a good thing to try, it might help it blend into the Python logo a bit better.

**Comment by CAM-Gerlach** [comment]
Per the [PSF Trademark Guidelines](https://www.python.org/psf/trademarks/), given this is a public site with a derived logo ,and the feather directly impinges inside the Python logomark, it would probably be advisable for @malemburg and the PSF trademarks committee to give this a look before merging.

**Comment by malemburg** [comment]
> Per the [PSF Trademark Guidelines](https://www.python.org/psf/trademarks/), given this is a public site with a derived logo ,and the feather directly impinges inside the Python logomark, it would probably be advisable for @malemburg and the PSF trademarks committee to give this a look before merging.

Please send the logo to the TM committee at psf-trademarks@python.org to get approval. As @CAM-Gerlach already mentioned, we won't be able to approve this variant. The feather will have to be fully separated from the Python logo, or placed inside one of the snakes.

**Comment by hugovk** [comment]
Thanks for checking! Let's close this.

@CAM-Gerlach Please could you remove it from Discord too, maybe replace with the standard logo?

**Comment by malemburg** [comment]
Uhm, I did not mean to spoil the fun. The logo looks nice, we'd just need to do a few iterations with the TM committee to make it compliant.

**Comment by hugovk** [comment]
No problem! We can iterate and re-open when we have something ready and approved :) Thanks!

**Comment by CAM-Gerlach** [comment]
> @CAM-Gerlach Please could you remove it from Discord too, maybe replace with the standard logo?

Since the Discord is a quasi-private community not publicly visible without an invite link as opposed to a public-facing website visible to the wider world, and at this point suddenly changing it temporarily would likely _create_ more consumer confusion then it would prevent (between the Python Docs discord and the Python core dev Discord, since they would suddenly have the same icon and the icon is the only visible-by-default disambguator between Discord servers), I would prefer if we could just wait a bit more to replace it with whatever conforming and approved variation we come up with, if possible.

**Comment by encukou** [comment]
If you'd like to experiment with positioning, the quill SVG is available [from svgsilh.com](https://svgsilh.com/000000/image/2027659.html) under CC0. It's simplified from [a Pixabay one](https://pixabay.com/vectors/vintage-feather-quill-write-1751222/) (uploaded in 2016, so CC0 per their [terms, §4](https://pixabay.com/service/terms/)).

**Pull request closed without merging**
