### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by hugovk**
For testing https://github.com/python/docs-community/pull/74.

----
:books: Documentation preview :books:: https://docs-community--75.org.readthedocs.build/en/75/

### CODE REVIEW

**Comment by hugovk** [comment]
It worked! :tada::book:🎖️ 

image

**Review by CAM-Gerlach — APPROVED** [review]
LGTM, thanks @hugovk ! The RTD link is a nice improvement, especially since RTD just started linking to the build page instead of the deploy preview and the link to the actual built docs preview is extremely small and very unintuitive to find (notably, it's _not_ the big "View docs" button up top, but rather a tiny "View docs" link squished together with several others in the right corner).

**Comment by humitos** [comment]
> especially since RTD just started linking to the build page instead of the deploy preview and the link to the actual built docs preview is extremely small and very unintuitive to find

He, this was not on purpose. It's a bug that we've failed to fix twice 😅 . Hopefully is gonna be fixed next week in our last attempt 🙃

**Comment by CAM-Gerlach** [comment]
Oh, heh, thanks. I actually don't think consistently linking to the build status page (which is what is linked when the build isn't complete) is _that_ unreasonable, its just one extra click (when it already takes several clicks to navigate to the `Details` link in the GitHub UI anyway) and can be avoided by using your (very nice, thanks) GitHub Action to add it to the OP.

What I did find to be more of a problem (not just now but several times previously in the past, when I clicked the `Details` link before the build was done) was how unintuitive and confusing it was that the big obvious `View Docs` button at the top of the build page didn't actually point to the docs built from that job, but rather it was a teeny tiny (apparently below WCAG guidelines) link (confusingly with the same "view docs" name as the big button) buried amidst a column of similar text. I'm pretty sure I never actually found completely the first few times I visited it, and only found it after a line by line search after this recent problem cropped up. It would be great if you could improve the UI there...

**Comment by humitos** [comment]
@CAM-Gerlach this is really good feedback. Thanks! Pinging @agjohnson who is working on a new completely re-defined version of our dashboard templates to keep this in mind.

**Comment by agjohnson** [comment]
> unintuitive and confusing it was that the big obvious View Docs button at the top of the build page didn't actually point to the docs built from that job

@CAM-Gerlach Agreed, all great points, and I share this frustration as well. I'm always hitting the wrong link in the dashboard. I've already addressed this in the dashboard redesign, but we're working towards a public beta there still.

In that project, I basically did what you're describing. The "View docs" button now brings you to the version that was built from the build, instead of the default version.

**Comment by CAM-Gerlach** [comment]
Great, thanks so much @humitos and @agjohnson ! As much as I sometimes complain too much, I'm glad the feedback is helpful! I've been consistently impressed by how responsive your team has been which gives me a lot more confidence in RTD as a platform. Thanks again!

**Comment by humitos** [comment]
I just checked how it's currently looking in our beta templates and it seems it's going to be a lot more intuitive where to click to read the version of the documentation that comes from the PR. I like it! 😄 

I'm _secretly_ sharing a screenshot of what I'm looking at with you, don't tell anyone 😅 

Screenshot_2023-03-06_10-40-01

**Comment by CAM-Gerlach** [comment]
Looking great so far! It looks like a pretty huge improvement over the current build pages, and seems to bring them all the way up to a similar standard as other mainstream CI platforms. Can't wait to see it in production!

**Comment by CAM-Gerlach** [comment]
(Oops, somehow <kbd>Ctrl</kbd>-<kbd>Enter</kbd> closed this instead of just submitting the comment...weird)

**Comment by CAM-Gerlach** [comment]
It seems the linkcheck now failed as a link to the RTD preview build of the devguide version status change has gone stale. Presumably, we can just replace that link to point to the live version, which includes those changes.

Also, I note some warnings related to NodeJS 12 actions being deprecated, which can be fixed by bumping the versions of the `checkout` and `setup-python` actions to the latest v3 and v4, accordingly.

Since this PR is fairly trivial and primarily for testing the CI and fixing minor issues, it seems reasonable to include both changes here.

**Comment by humitos** [comment]
Hi! I wanted to come back here and let you know that it's possible to start playing a bit with our new **beta dashboard**[^1] at https://beta.readthedocs.org/. It's not "100% public" yet. You need to manually create a cookie in your side with the key `beta` and the value `true` (I've done this in Firefox by pressing F12 -> Storage -> Cookies -> "Plus" sign) . That's all 😄 

Feel free to open an issue in our repository with your feedback in case you have any. I'm happy to receive more general feedback and also specific feedback. However, keep in mind that things can drastically change and nothing is written in stone 😄 

[^1]: there some pages that are not implemented yet and things that may return 500, but the ones that are there, look really good 💅🏼

**Comment by CAM-Gerlach** [comment]
Hi @humitos ! Thanks for the update! After following your instructions, I was indeed able to access the new [beta page for this PR](https://beta.readthedocs.org/projects/docs-community/builds/19686498/) and it looks great overall! MASSIVE improvement, even better than I hoped!

Some minor points of feedback:

* Above the log display, `Output` looks like a tab/button like the others and is "selected", but there appears to be no way to de-select it or switch to another, which was a little confusing. Not 100% sure what specifically would fix this, though, other than maybe making it look a bit more distinct from the others.
* Then, the `Raw Log` "tab" suddenly navigated me away from the page entirely to a plain text file rather than toggling a "raw" view in the existing log below, as I would expect based on its placement, symbology and context. As this also opens something "different", like the docs site, I'd suggest moving it to the right next to the "View Docs" button, which helps imply that like the latter, it opens something different rather than toggling something on the existing page.
* Finally, the `Debug` toggles the full debug output in the existing log window; this seems reasonable given its placement, but it took a couple tries to figure out precisely what it did. I suggest adding a brief tooltip that explains it.
* Though it is still pretty visible as it is, especially if `Raw Log` is moved next to it, maybe make the `View docs` button blue (or an appropriate accent color from your palette) to make it more prominently visible.
* It would be nice to show the exact build time, as before. In the old dashboard, it says "30 seconds" for the build time, which I certainly wouldn't call "a few seconds".
* I liked the additional information shown when clicking the `...` next to the community, but the layout seemed rather space-inefficient and right-side heavy/crowded, especially on desktop:

  image
  
  Maybe move maintainers to, e.g., top right of the project name to avoid stacking the right side so much?
  
  image

Hopefully this is helpful; thanks!

**Pull request merged**
